// Copyright 2020 Lingfei Kong <colin404@foxmail.com>. All rights reserved.
// Use of this source code is governed by a MIT style
// license that can be found in the LICENSE file.

// Code generated by "codegen -type=int /Users/max/Documents/coding/Backend/Golang/Personal/hurricane/internal/pkg/code"; DO NOT EDIT.

package code

// init register error codes defines in this source code to `github.com/marmotedu/errors`
func init() {
	// register(ErrDatabase, 500, "Database error")
	// register(ErrUnauthorized, 401, "Unauthorized access")
	// register(ErrNotFound, 404, "Resource not found")
	// register(ErrBadRequest, 400, "Bad request")
	// register(ErrForbidden, 403, "Access forbidden")
	// register(ErrInternalServerError, 500, "Internal server error")
}
